# permissions for end users to edit nodesystemconfigupdates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nodesystemconfigupdate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: masters-degree
    app.kubernetes.io/part-of: masters-degree
    app.kubernetes.io/managed-by: kustomize
  name: nodesystemconfigupdate-editor-role
rules:
- apiGroups:
  - system.masters.degree
  resources:
  - nodesystemconfigupdates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - system.masters.degree
  resources:
  - nodesystemconfigupdates/status
  verbs:
  - get
