---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
- apiGroups:
  - system.masters.degree
  resources:
  - nodesystemconfigupdates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - system.masters.degree
  resources:
  - nodesystemconfigupdates/finalizers
  verbs:
  - update
- apiGroups:
  - system.masters.degree
  resources:
  - nodesystemconfigupdates/status
  verbs:
  - get
  - patch
  - update
