apiVersion: system.masters.degree/v1alpha1
kind: NodeSystemConfigUpdate
metadata:
  labels:
    app.kubernetes.io/name: nodesystemconfigupdate
  annotations:
    autoremediate: "true"
  name: nodesystemconfigupdate-sample
spec:
  nodeSelector:
    highTp: "true"
    mellanoxNIC: "true"
  hugepages:
    hugepages-1Gi: 0
    hugepages-2Mi: 2
  sysctl:
    fs:
      inotify:
        max_queued_events: 16384
        max_user_instances: 128
        max_user_watches: 8192
    kernel:
      core_pattern: "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h"
      sched_rt_runtime_us: 950002
    net:
      core:
        rmem_default: 212992
        rmem_max: 212992
        wmem_default: 212992
        wmem_max: 212992
      ipv4:
        tcp_mem: [44394, 59194, 88777]
        tcp_rmem: [4096, 131822, 6291456]
        tcp_slow_start_after_idle: 1
        tcp_wmem: [4096, 16384, 4194304]
        udp_mem: [88791, 118389, 177582]
        udp_rmem_min: 4095
        udp_wmem_min: 4096
      netfilter:
        nf_conntrack_tcp_timeout_max_retrans: 300 
        nf_conntrack_tcp_timeout_unacknowledged: 300
#      sctp:
#        auth_enable: 0
#        sctp_mem: [24709599, 32946135, 49419198]
    vm:
      max_map_count: 65530
  

#status:
#  lastUpdateTime: string
#  nodeName: []string
#  nodesConfigured: bool