//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNet) DeepCopyInto(out *CoreNet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNet.
func (in *CoreNet) DeepCopy() *CoreNet {
	if in == nil {
		return nil
	}
	out := new(CoreNet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FsSysctl) DeepCopyInto(out *FsSysctl) {
	*out = *in
	out.Inotify = in.Inotify
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FsSysctl.
func (in *FsSysctl) DeepCopy() *FsSysctl {
	if in == nil {
		return nil
	}
	out := new(FsSysctl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InotifyFs) DeepCopyInto(out *InotifyFs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InotifyFs.
func (in *InotifyFs) DeepCopy() *InotifyFs {
	if in == nil {
		return nil
	}
	out := new(InotifyFs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ipv4Net) DeepCopyInto(out *Ipv4Net) {
	*out = *in
	if in.TcpMem != nil {
		in, out := &in.TcpMem, &out.TcpMem
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.TcpRmem != nil {
		in, out := &in.TcpRmem, &out.TcpRmem
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.TcpWmem != nil {
		in, out := &in.TcpWmem, &out.TcpWmem
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.UdpMem != nil {
		in, out := &in.UdpMem, &out.UdpMem
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ipv4Net.
func (in *Ipv4Net) DeepCopy() *Ipv4Net {
	if in == nil {
		return nil
	}
	out := new(Ipv4Net)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KernelSysctl) DeepCopyInto(out *KernelSysctl) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KernelSysctl.
func (in *KernelSysctl) DeepCopy() *KernelSysctl {
	if in == nil {
		return nil
	}
	out := new(KernelSysctl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetSysctl) DeepCopyInto(out *NetSysctl) {
	*out = *in
	out.Core = in.Core
	in.Ipv4.DeepCopyInto(&out.Ipv4)
	out.Netfilter = in.Netfilter
	in.Sctp.DeepCopyInto(&out.Sctp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetSysctl.
func (in *NetSysctl) DeepCopy() *NetSysctl {
	if in == nil {
		return nil
	}
	out := new(NetSysctl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetfilterNet) DeepCopyInto(out *NetfilterNet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetfilterNet.
func (in *NetfilterNet) DeepCopy() *NetfilterNet {
	if in == nil {
		return nil
	}
	out := new(NetfilterNet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfigUpdate) DeepCopyInto(out *NodeSystemConfigUpdate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfigUpdate.
func (in *NodeSystemConfigUpdate) DeepCopy() *NodeSystemConfigUpdate {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfigUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSystemConfigUpdate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfigUpdateList) DeepCopyInto(out *NodeSystemConfigUpdateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSystemConfigUpdate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfigUpdateList.
func (in *NodeSystemConfigUpdateList) DeepCopy() *NodeSystemConfigUpdateList {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfigUpdateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSystemConfigUpdateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfigUpdateSpec) DeepCopyInto(out *NodeSystemConfigUpdateSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Sysctl.DeepCopyInto(&out.Sysctl)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfigUpdateSpec.
func (in *NodeSystemConfigUpdateSpec) DeepCopy() *NodeSystemConfigUpdateSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfigUpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfigUpdateStatus) DeepCopyInto(out *NodeSystemConfigUpdateStatus) {
	*out = *in
	if in.NodesConfigured != nil {
		in, out := &in.NodesConfigured, &out.NodesConfigured
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfigUpdateStatus.
func (in *NodeSystemConfigUpdateStatus) DeepCopy() *NodeSystemConfigUpdateStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfigUpdateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SctpNet) DeepCopyInto(out *SctpNet) {
	*out = *in
	if in.SctpMem != nil {
		in, out := &in.SctpMem, &out.SctpMem
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SctpNet.
func (in *SctpNet) DeepCopy() *SctpNet {
	if in == nil {
		return nil
	}
	out := new(SctpNet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sysctl) DeepCopyInto(out *Sysctl) {
	*out = *in
	out.Fs = in.Fs
	out.Kernel = in.Kernel
	in.Net.DeepCopyInto(&out.Net)
	out.Vm = in.Vm
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sysctl.
func (in *Sysctl) DeepCopy() *Sysctl {
	if in == nil {
		return nil
	}
	out := new(Sysctl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmSysctl) DeepCopyInto(out *VmSysctl) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmSysctl.
func (in *VmSysctl) DeepCopy() *VmSysctl {
	if in == nil {
		return nil
	}
	out := new(VmSysctl)
	in.DeepCopyInto(out)
	return out
}
